@baseUrl = http://localhost:5000/api/ops

###
GET {{baseUrl}}

###
GET {{baseUrl}}/:id

###
POST {{baseUrl}}
Content-Type: application/json
Authorization: Bearer <token>

{
  "concept": "test",
  "amount": 100,
  "typeId": 1
}

###
PUT {{baseUrl}}/:id
Content-Type: application/json
Authorization: Bearer <token>

{
  "concept": "test update",
  "amount": 550,
  "typeId": 1
}


###
DELETE {{baseUrl}}/:id
Authorization: Bearer <token>