@baseUrl = http://localhost:5000/api/ops

###
GET {{baseUrl}}

###
GET {{baseUrl}}/123123123123


###
POST {{baseUrl}}
Content-Type: application/json

{
  "concept": "testing",
  "amount": 20.5,
  "typeId": 2
}

###
PUT {{baseUrl}}/1
Content-Type: application/json

{
  "concept": "testing update",
  "amount": 10,
  "typeId": 2
}


###
DELETE {{baseUrl}}/1